# Add your own tasks in files placed in lib/tasks ending in .rake,
# for example lib/tasks/capistrano.rake, and they will automatically be available to Rake.

require File.expand_path('../config/application', __FILE__)

Rails.application.load_tasks

namespace :demo do
  desc "Init addmin user"
  task setup: :environment do
    puts 'Create Admin account'
    account = Locomotive::Account.new email: "demo@shopinvader.com", password: "akretion", password_confirmation: "akretion", name: "Demo"
    account.api_key = 'd49cd50f6f0d2b163f48fc73cb249f0244c37074'
    account.save!

    puts 'Create demo Site'
    site = Locomotive::Site.create! name: "Shopinvader", handle: "shopinvader", domains: ["localhost"], locales: [:en, :fr]
    site.memberships.build account: account, role: 'admin'
    site.save!
  end
end
